/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment/index'
import { Route as AuthenticatedCoffeesIndexRouteImport } from './routes/_authenticated/coffees/index'
import { Route as AuthenticatedBrewsIndexRouteImport } from './routes/_authenticated/brews/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedPouroverNewRouteImport } from './routes/_authenticated/pourover/new'
import { Route as AuthenticatedFrenchpressNewRouteImport } from './routes/_authenticated/frenchpress/new'
import { Route as AuthenticatedEspressoNewRouteImport } from './routes/_authenticated/espresso/new'
import { Route as AuthenticatedCoffeesNewRouteImport } from './routes/_authenticated/coffees/new'
import { Route as AuthenticatedAeropressNewRouteImport } from './routes/_authenticated/aeropress/new'
import { Route as AuthenticatedPouroverBrewIdEditRouteImport } from './routes/_authenticated/pourover/$brewId.edit'
import { Route as AuthenticatedFrenchpressBrewIdEditRouteImport } from './routes/_authenticated/frenchpress/$brewId.edit'
import { Route as AuthenticatedEspressoShotIdEditRouteImport } from './routes/_authenticated/espresso/$shotId.edit'
import { Route as AuthenticatedEquipmentGrindersNewRouteImport } from './routes/_authenticated/equipment/grinders/new'
import { Route as AuthenticatedEquipmentBrewingDevicesNewRouteImport } from './routes/_authenticated/equipment/brewing-devices/new'
import { Route as AuthenticatedCoffeesCoffeeIdEditRouteImport } from './routes/_authenticated/coffees/$coffeeId.edit'
import { Route as AuthenticatedAeropressBrewIdEditRouteImport } from './routes/_authenticated/aeropress/$brewId.edit'
import { Route as AuthenticatedEquipmentGrindersGrinderIdEditRouteImport } from './routes/_authenticated/equipment/grinders/$grinderId.edit'
import { Route as AuthenticatedEquipmentBrewingDevicesDeviceIdEditRouteImport } from './routes/_authenticated/equipment/brewing-devices/$deviceId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoffeesIndexRoute =
  AuthenticatedCoffeesIndexRouteImport.update({
    id: '/coffees/',
    path: '/coffees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBrewsIndexRoute = AuthenticatedBrewsIndexRouteImport.update({
  id: '/brews/',
  path: '/brews/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPouroverNewRoute =
  AuthenticatedPouroverNewRouteImport.update({
    id: '/pourover/new',
    path: '/pourover/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrenchpressNewRoute =
  AuthenticatedFrenchpressNewRouteImport.update({
    id: '/frenchpress/new',
    path: '/frenchpress/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEspressoNewRoute =
  AuthenticatedEspressoNewRouteImport.update({
    id: '/espresso/new',
    path: '/espresso/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoffeesNewRoute = AuthenticatedCoffeesNewRouteImport.update({
  id: '/coffees/new',
  path: '/coffees/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAeropressNewRoute =
  AuthenticatedAeropressNewRouteImport.update({
    id: '/aeropress/new',
    path: '/aeropress/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPouroverBrewIdEditRoute =
  AuthenticatedPouroverBrewIdEditRouteImport.update({
    id: '/pourover/$brewId/edit',
    path: '/pourover/$brewId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrenchpressBrewIdEditRoute =
  AuthenticatedFrenchpressBrewIdEditRouteImport.update({
    id: '/frenchpress/$brewId/edit',
    path: '/frenchpress/$brewId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEspressoShotIdEditRoute =
  AuthenticatedEspressoShotIdEditRouteImport.update({
    id: '/espresso/$shotId/edit',
    path: '/espresso/$shotId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentGrindersNewRoute =
  AuthenticatedEquipmentGrindersNewRouteImport.update({
    id: '/equipment/grinders/new',
    path: '/equipment/grinders/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentBrewingDevicesNewRoute =
  AuthenticatedEquipmentBrewingDevicesNewRouteImport.update({
    id: '/equipment/brewing-devices/new',
    path: '/equipment/brewing-devices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoffeesCoffeeIdEditRoute =
  AuthenticatedCoffeesCoffeeIdEditRouteImport.update({
    id: '/coffees/$coffeeId/edit',
    path: '/coffees/$coffeeId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAeropressBrewIdEditRoute =
  AuthenticatedAeropressBrewIdEditRouteImport.update({
    id: '/aeropress/$brewId/edit',
    path: '/aeropress/$brewId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentGrindersGrinderIdEditRoute =
  AuthenticatedEquipmentGrindersGrinderIdEditRouteImport.update({
    id: '/equipment/grinders/$grinderId/edit',
    path: '/equipment/grinders/$grinderId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute =
  AuthenticatedEquipmentBrewingDevicesDeviceIdEditRouteImport.update({
    id: '/equipment/brewing-devices/$deviceId/edit',
    path: '/equipment/brewing-devices/$deviceId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aeropress/new': typeof AuthenticatedAeropressNewRoute
  '/coffees/new': typeof AuthenticatedCoffeesNewRoute
  '/espresso/new': typeof AuthenticatedEspressoNewRoute
  '/frenchpress/new': typeof AuthenticatedFrenchpressNewRoute
  '/pourover/new': typeof AuthenticatedPouroverNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/brews/': typeof AuthenticatedBrewsIndexRoute
  '/coffees/': typeof AuthenticatedCoffeesIndexRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/aeropress/$brewId/edit': typeof AuthenticatedAeropressBrewIdEditRoute
  '/coffees/$coffeeId/edit': typeof AuthenticatedCoffeesCoffeeIdEditRoute
  '/equipment/brewing-devices/new': typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  '/equipment/grinders/new': typeof AuthenticatedEquipmentGrindersNewRoute
  '/espresso/$shotId/edit': typeof AuthenticatedEspressoShotIdEditRoute
  '/frenchpress/$brewId/edit': typeof AuthenticatedFrenchpressBrewIdEditRoute
  '/pourover/$brewId/edit': typeof AuthenticatedPouroverBrewIdEditRoute
  '/equipment/brewing-devices/$deviceId/edit': typeof AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute
  '/equipment/grinders/$grinderId/edit': typeof AuthenticatedEquipmentGrindersGrinderIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aeropress/new': typeof AuthenticatedAeropressNewRoute
  '/coffees/new': typeof AuthenticatedCoffeesNewRoute
  '/espresso/new': typeof AuthenticatedEspressoNewRoute
  '/frenchpress/new': typeof AuthenticatedFrenchpressNewRoute
  '/pourover/new': typeof AuthenticatedPouroverNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/brews': typeof AuthenticatedBrewsIndexRoute
  '/coffees': typeof AuthenticatedCoffeesIndexRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
  '/aeropress/$brewId/edit': typeof AuthenticatedAeropressBrewIdEditRoute
  '/coffees/$coffeeId/edit': typeof AuthenticatedCoffeesCoffeeIdEditRoute
  '/equipment/brewing-devices/new': typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  '/equipment/grinders/new': typeof AuthenticatedEquipmentGrindersNewRoute
  '/espresso/$shotId/edit': typeof AuthenticatedEspressoShotIdEditRoute
  '/frenchpress/$brewId/edit': typeof AuthenticatedFrenchpressBrewIdEditRoute
  '/pourover/$brewId/edit': typeof AuthenticatedPouroverBrewIdEditRoute
  '/equipment/brewing-devices/$deviceId/edit': typeof AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute
  '/equipment/grinders/$grinderId/edit': typeof AuthenticatedEquipmentGrindersGrinderIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/aeropress/new': typeof AuthenticatedAeropressNewRoute
  '/_authenticated/coffees/new': typeof AuthenticatedCoffeesNewRoute
  '/_authenticated/espresso/new': typeof AuthenticatedEspressoNewRoute
  '/_authenticated/frenchpress/new': typeof AuthenticatedFrenchpressNewRoute
  '/_authenticated/pourover/new': typeof AuthenticatedPouroverNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/brews/': typeof AuthenticatedBrewsIndexRoute
  '/_authenticated/coffees/': typeof AuthenticatedCoffeesIndexRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/_authenticated/aeropress/$brewId/edit': typeof AuthenticatedAeropressBrewIdEditRoute
  '/_authenticated/coffees/$coffeeId/edit': typeof AuthenticatedCoffeesCoffeeIdEditRoute
  '/_authenticated/equipment/brewing-devices/new': typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  '/_authenticated/equipment/grinders/new': typeof AuthenticatedEquipmentGrindersNewRoute
  '/_authenticated/espresso/$shotId/edit': typeof AuthenticatedEspressoShotIdEditRoute
  '/_authenticated/frenchpress/$brewId/edit': typeof AuthenticatedFrenchpressBrewIdEditRoute
  '/_authenticated/pourover/$brewId/edit': typeof AuthenticatedPouroverBrewIdEditRoute
  '/_authenticated/equipment/brewing-devices/$deviceId/edit': typeof AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute
  '/_authenticated/equipment/grinders/$grinderId/edit': typeof AuthenticatedEquipmentGrindersGrinderIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aeropress/new'
    | '/coffees/new'
    | '/espresso/new'
    | '/frenchpress/new'
    | '/pourover/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/brews/'
    | '/coffees/'
    | '/equipment/'
    | '/aeropress/$brewId/edit'
    | '/coffees/$coffeeId/edit'
    | '/equipment/brewing-devices/new'
    | '/equipment/grinders/new'
    | '/espresso/$shotId/edit'
    | '/frenchpress/$brewId/edit'
    | '/pourover/$brewId/edit'
    | '/equipment/brewing-devices/$deviceId/edit'
    | '/equipment/grinders/$grinderId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aeropress/new'
    | '/coffees/new'
    | '/espresso/new'
    | '/frenchpress/new'
    | '/pourover/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/brews'
    | '/coffees'
    | '/equipment'
    | '/aeropress/$brewId/edit'
    | '/coffees/$coffeeId/edit'
    | '/equipment/brewing-devices/new'
    | '/equipment/grinders/new'
    | '/espresso/$shotId/edit'
    | '/frenchpress/$brewId/edit'
    | '/pourover/$brewId/edit'
    | '/equipment/brewing-devices/$deviceId/edit'
    | '/equipment/grinders/$grinderId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/aeropress/new'
    | '/_authenticated/coffees/new'
    | '/_authenticated/espresso/new'
    | '/_authenticated/frenchpress/new'
    | '/_authenticated/pourover/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/brews/'
    | '/_authenticated/coffees/'
    | '/_authenticated/equipment/'
    | '/_authenticated/aeropress/$brewId/edit'
    | '/_authenticated/coffees/$coffeeId/edit'
    | '/_authenticated/equipment/brewing-devices/new'
    | '/_authenticated/equipment/grinders/new'
    | '/_authenticated/espresso/$shotId/edit'
    | '/_authenticated/frenchpress/$brewId/edit'
    | '/_authenticated/pourover/$brewId/edit'
    | '/_authenticated/equipment/brewing-devices/$deviceId/edit'
    | '/_authenticated/equipment/grinders/$grinderId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coffees/': {
      id: '/_authenticated/coffees/'
      path: '/coffees'
      fullPath: '/coffees/'
      preLoaderRoute: typeof AuthenticatedCoffeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brews/': {
      id: '/_authenticated/brews/'
      path: '/brews'
      fullPath: '/brews/'
      preLoaderRoute: typeof AuthenticatedBrewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pourover/new': {
      id: '/_authenticated/pourover/new'
      path: '/pourover/new'
      fullPath: '/pourover/new'
      preLoaderRoute: typeof AuthenticatedPouroverNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frenchpress/new': {
      id: '/_authenticated/frenchpress/new'
      path: '/frenchpress/new'
      fullPath: '/frenchpress/new'
      preLoaderRoute: typeof AuthenticatedFrenchpressNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espresso/new': {
      id: '/_authenticated/espresso/new'
      path: '/espresso/new'
      fullPath: '/espresso/new'
      preLoaderRoute: typeof AuthenticatedEspressoNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coffees/new': {
      id: '/_authenticated/coffees/new'
      path: '/coffees/new'
      fullPath: '/coffees/new'
      preLoaderRoute: typeof AuthenticatedCoffeesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aeropress/new': {
      id: '/_authenticated/aeropress/new'
      path: '/aeropress/new'
      fullPath: '/aeropress/new'
      preLoaderRoute: typeof AuthenticatedAeropressNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pourover/$brewId/edit': {
      id: '/_authenticated/pourover/$brewId/edit'
      path: '/pourover/$brewId/edit'
      fullPath: '/pourover/$brewId/edit'
      preLoaderRoute: typeof AuthenticatedPouroverBrewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frenchpress/$brewId/edit': {
      id: '/_authenticated/frenchpress/$brewId/edit'
      path: '/frenchpress/$brewId/edit'
      fullPath: '/frenchpress/$brewId/edit'
      preLoaderRoute: typeof AuthenticatedFrenchpressBrewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espresso/$shotId/edit': {
      id: '/_authenticated/espresso/$shotId/edit'
      path: '/espresso/$shotId/edit'
      fullPath: '/espresso/$shotId/edit'
      preLoaderRoute: typeof AuthenticatedEspressoShotIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/grinders/new': {
      id: '/_authenticated/equipment/grinders/new'
      path: '/equipment/grinders/new'
      fullPath: '/equipment/grinders/new'
      preLoaderRoute: typeof AuthenticatedEquipmentGrindersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/brewing-devices/new': {
      id: '/_authenticated/equipment/brewing-devices/new'
      path: '/equipment/brewing-devices/new'
      fullPath: '/equipment/brewing-devices/new'
      preLoaderRoute: typeof AuthenticatedEquipmentBrewingDevicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coffees/$coffeeId/edit': {
      id: '/_authenticated/coffees/$coffeeId/edit'
      path: '/coffees/$coffeeId/edit'
      fullPath: '/coffees/$coffeeId/edit'
      preLoaderRoute: typeof AuthenticatedCoffeesCoffeeIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aeropress/$brewId/edit': {
      id: '/_authenticated/aeropress/$brewId/edit'
      path: '/aeropress/$brewId/edit'
      fullPath: '/aeropress/$brewId/edit'
      preLoaderRoute: typeof AuthenticatedAeropressBrewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/grinders/$grinderId/edit': {
      id: '/_authenticated/equipment/grinders/$grinderId/edit'
      path: '/equipment/grinders/$grinderId/edit'
      fullPath: '/equipment/grinders/$grinderId/edit'
      preLoaderRoute: typeof AuthenticatedEquipmentGrindersGrinderIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/brewing-devices/$deviceId/edit': {
      id: '/_authenticated/equipment/brewing-devices/$deviceId/edit'
      path: '/equipment/brewing-devices/$deviceId/edit'
      fullPath: '/equipment/brewing-devices/$deviceId/edit'
      preLoaderRoute: typeof AuthenticatedEquipmentBrewingDevicesDeviceIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAeropressNewRoute: typeof AuthenticatedAeropressNewRoute
  AuthenticatedCoffeesNewRoute: typeof AuthenticatedCoffeesNewRoute
  AuthenticatedEspressoNewRoute: typeof AuthenticatedEspressoNewRoute
  AuthenticatedFrenchpressNewRoute: typeof AuthenticatedFrenchpressNewRoute
  AuthenticatedPouroverNewRoute: typeof AuthenticatedPouroverNewRoute
  AuthenticatedBrewsIndexRoute: typeof AuthenticatedBrewsIndexRoute
  AuthenticatedCoffeesIndexRoute: typeof AuthenticatedCoffeesIndexRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
  AuthenticatedAeropressBrewIdEditRoute: typeof AuthenticatedAeropressBrewIdEditRoute
  AuthenticatedCoffeesCoffeeIdEditRoute: typeof AuthenticatedCoffeesCoffeeIdEditRoute
  AuthenticatedEquipmentBrewingDevicesNewRoute: typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  AuthenticatedEquipmentGrindersNewRoute: typeof AuthenticatedEquipmentGrindersNewRoute
  AuthenticatedEspressoShotIdEditRoute: typeof AuthenticatedEspressoShotIdEditRoute
  AuthenticatedFrenchpressBrewIdEditRoute: typeof AuthenticatedFrenchpressBrewIdEditRoute
  AuthenticatedPouroverBrewIdEditRoute: typeof AuthenticatedPouroverBrewIdEditRoute
  AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute: typeof AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute
  AuthenticatedEquipmentGrindersGrinderIdEditRoute: typeof AuthenticatedEquipmentGrindersGrinderIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAeropressNewRoute: AuthenticatedAeropressNewRoute,
  AuthenticatedCoffeesNewRoute: AuthenticatedCoffeesNewRoute,
  AuthenticatedEspressoNewRoute: AuthenticatedEspressoNewRoute,
  AuthenticatedFrenchpressNewRoute: AuthenticatedFrenchpressNewRoute,
  AuthenticatedPouroverNewRoute: AuthenticatedPouroverNewRoute,
  AuthenticatedBrewsIndexRoute: AuthenticatedBrewsIndexRoute,
  AuthenticatedCoffeesIndexRoute: AuthenticatedCoffeesIndexRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
  AuthenticatedAeropressBrewIdEditRoute: AuthenticatedAeropressBrewIdEditRoute,
  AuthenticatedCoffeesCoffeeIdEditRoute: AuthenticatedCoffeesCoffeeIdEditRoute,
  AuthenticatedEquipmentBrewingDevicesNewRoute:
    AuthenticatedEquipmentBrewingDevicesNewRoute,
  AuthenticatedEquipmentGrindersNewRoute:
    AuthenticatedEquipmentGrindersNewRoute,
  AuthenticatedEspressoShotIdEditRoute: AuthenticatedEspressoShotIdEditRoute,
  AuthenticatedFrenchpressBrewIdEditRoute:
    AuthenticatedFrenchpressBrewIdEditRoute,
  AuthenticatedPouroverBrewIdEditRoute: AuthenticatedPouroverBrewIdEditRoute,
  AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute:
    AuthenticatedEquipmentBrewingDevicesDeviceIdEditRoute,
  AuthenticatedEquipmentGrindersGrinderIdEditRoute:
    AuthenticatedEquipmentGrindersGrinderIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
