/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEspressoIndexRouteImport } from './routes/_authenticated/espresso/index'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment/index'
import { Route as AuthenticatedCoffeesIndexRouteImport } from './routes/_authenticated/coffees/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedEspressoNewRouteImport } from './routes/_authenticated/espresso/new'
import { Route as AuthenticatedCoffeesNewRouteImport } from './routes/_authenticated/coffees/new'
import { Route as AuthenticatedEspressoShotIdEditRouteImport } from './routes/_authenticated/espresso/$shotId.edit'
import { Route as AuthenticatedEquipmentGrindersNewRouteImport } from './routes/_authenticated/equipment/grinders/new'
import { Route as AuthenticatedEquipmentBrewingDevicesNewRouteImport } from './routes/_authenticated/equipment/brewing-devices/new'
import { Route as AuthenticatedCoffeesCoffeeIdEditRouteImport } from './routes/_authenticated/coffees/$coffeeId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspressoIndexRoute =
  AuthenticatedEspressoIndexRouteImport.update({
    id: '/espresso/',
    path: '/espresso/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoffeesIndexRoute =
  AuthenticatedCoffeesIndexRouteImport.update({
    id: '/coffees/',
    path: '/coffees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspressoNewRoute =
  AuthenticatedEspressoNewRouteImport.update({
    id: '/espresso/new',
    path: '/espresso/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoffeesNewRoute = AuthenticatedCoffeesNewRouteImport.update({
  id: '/coffees/new',
  path: '/coffees/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEspressoShotIdEditRoute =
  AuthenticatedEspressoShotIdEditRouteImport.update({
    id: '/espresso/$shotId/edit',
    path: '/espresso/$shotId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentGrindersNewRoute =
  AuthenticatedEquipmentGrindersNewRouteImport.update({
    id: '/equipment/grinders/new',
    path: '/equipment/grinders/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentBrewingDevicesNewRoute =
  AuthenticatedEquipmentBrewingDevicesNewRouteImport.update({
    id: '/equipment/brewing-devices/new',
    path: '/equipment/brewing-devices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoffeesCoffeeIdEditRoute =
  AuthenticatedCoffeesCoffeeIdEditRouteImport.update({
    id: '/coffees/$coffeeId/edit',
    path: '/coffees/$coffeeId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coffees/new': typeof AuthenticatedCoffeesNewRoute
  '/espresso/new': typeof AuthenticatedEspressoNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/coffees/': typeof AuthenticatedCoffeesIndexRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/espresso/': typeof AuthenticatedEspressoIndexRoute
  '/coffees/$coffeeId/edit': typeof AuthenticatedCoffeesCoffeeIdEditRoute
  '/equipment/brewing-devices/new': typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  '/equipment/grinders/new': typeof AuthenticatedEquipmentGrindersNewRoute
  '/espresso/$shotId/edit': typeof AuthenticatedEspressoShotIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coffees/new': typeof AuthenticatedCoffeesNewRoute
  '/espresso/new': typeof AuthenticatedEspressoNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/coffees': typeof AuthenticatedCoffeesIndexRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
  '/espresso': typeof AuthenticatedEspressoIndexRoute
  '/coffees/$coffeeId/edit': typeof AuthenticatedCoffeesCoffeeIdEditRoute
  '/equipment/brewing-devices/new': typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  '/equipment/grinders/new': typeof AuthenticatedEquipmentGrindersNewRoute
  '/espresso/$shotId/edit': typeof AuthenticatedEspressoShotIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/coffees/new': typeof AuthenticatedCoffeesNewRoute
  '/_authenticated/espresso/new': typeof AuthenticatedEspressoNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/coffees/': typeof AuthenticatedCoffeesIndexRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/_authenticated/espresso/': typeof AuthenticatedEspressoIndexRoute
  '/_authenticated/coffees/$coffeeId/edit': typeof AuthenticatedCoffeesCoffeeIdEditRoute
  '/_authenticated/equipment/brewing-devices/new': typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  '/_authenticated/equipment/grinders/new': typeof AuthenticatedEquipmentGrindersNewRoute
  '/_authenticated/espresso/$shotId/edit': typeof AuthenticatedEspressoShotIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coffees/new'
    | '/espresso/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/coffees/'
    | '/equipment/'
    | '/espresso/'
    | '/coffees/$coffeeId/edit'
    | '/equipment/brewing-devices/new'
    | '/equipment/grinders/new'
    | '/espresso/$shotId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coffees/new'
    | '/espresso/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/coffees'
    | '/equipment'
    | '/espresso'
    | '/coffees/$coffeeId/edit'
    | '/equipment/brewing-devices/new'
    | '/equipment/grinders/new'
    | '/espresso/$shotId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/coffees/new'
    | '/_authenticated/espresso/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/coffees/'
    | '/_authenticated/equipment/'
    | '/_authenticated/espresso/'
    | '/_authenticated/coffees/$coffeeId/edit'
    | '/_authenticated/equipment/brewing-devices/new'
    | '/_authenticated/equipment/grinders/new'
    | '/_authenticated/espresso/$shotId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espresso/': {
      id: '/_authenticated/espresso/'
      path: '/espresso'
      fullPath: '/espresso/'
      preLoaderRoute: typeof AuthenticatedEspressoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coffees/': {
      id: '/_authenticated/coffees/'
      path: '/coffees'
      fullPath: '/coffees/'
      preLoaderRoute: typeof AuthenticatedCoffeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espresso/new': {
      id: '/_authenticated/espresso/new'
      path: '/espresso/new'
      fullPath: '/espresso/new'
      preLoaderRoute: typeof AuthenticatedEspressoNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coffees/new': {
      id: '/_authenticated/coffees/new'
      path: '/coffees/new'
      fullPath: '/coffees/new'
      preLoaderRoute: typeof AuthenticatedCoffeesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espresso/$shotId/edit': {
      id: '/_authenticated/espresso/$shotId/edit'
      path: '/espresso/$shotId/edit'
      fullPath: '/espresso/$shotId/edit'
      preLoaderRoute: typeof AuthenticatedEspressoShotIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/grinders/new': {
      id: '/_authenticated/equipment/grinders/new'
      path: '/equipment/grinders/new'
      fullPath: '/equipment/grinders/new'
      preLoaderRoute: typeof AuthenticatedEquipmentGrindersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/brewing-devices/new': {
      id: '/_authenticated/equipment/brewing-devices/new'
      path: '/equipment/brewing-devices/new'
      fullPath: '/equipment/brewing-devices/new'
      preLoaderRoute: typeof AuthenticatedEquipmentBrewingDevicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coffees/$coffeeId/edit': {
      id: '/_authenticated/coffees/$coffeeId/edit'
      path: '/coffees/$coffeeId/edit'
      fullPath: '/coffees/$coffeeId/edit'
      preLoaderRoute: typeof AuthenticatedCoffeesCoffeeIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCoffeesNewRoute: typeof AuthenticatedCoffeesNewRoute
  AuthenticatedEspressoNewRoute: typeof AuthenticatedEspressoNewRoute
  AuthenticatedCoffeesIndexRoute: typeof AuthenticatedCoffeesIndexRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
  AuthenticatedEspressoIndexRoute: typeof AuthenticatedEspressoIndexRoute
  AuthenticatedCoffeesCoffeeIdEditRoute: typeof AuthenticatedCoffeesCoffeeIdEditRoute
  AuthenticatedEquipmentBrewingDevicesNewRoute: typeof AuthenticatedEquipmentBrewingDevicesNewRoute
  AuthenticatedEquipmentGrindersNewRoute: typeof AuthenticatedEquipmentGrindersNewRoute
  AuthenticatedEspressoShotIdEditRoute: typeof AuthenticatedEspressoShotIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoffeesNewRoute: AuthenticatedCoffeesNewRoute,
  AuthenticatedEspressoNewRoute: AuthenticatedEspressoNewRoute,
  AuthenticatedCoffeesIndexRoute: AuthenticatedCoffeesIndexRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
  AuthenticatedEspressoIndexRoute: AuthenticatedEspressoIndexRoute,
  AuthenticatedCoffeesCoffeeIdEditRoute: AuthenticatedCoffeesCoffeeIdEditRoute,
  AuthenticatedEquipmentBrewingDevicesNewRoute:
    AuthenticatedEquipmentBrewingDevicesNewRoute,
  AuthenticatedEquipmentGrindersNewRoute:
    AuthenticatedEquipmentGrindersNewRoute,
  AuthenticatedEspressoShotIdEditRoute: AuthenticatedEspressoShotIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
